# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LSQf <- function(cvec, SiCell, data, p, k, B, estGrid, weights) {
    .Call(`_mGSFPCA_LSQf`, cvec, SiCell, data, p, k, B, estGrid, weights)
}

LSQg <- function(cvec, SiCell, data, p, k, B, estGrid, weights) {
    .Call(`_mGSFPCA_LSQg`, cvec, SiCell, data, p, k, B, estGrid, weights)
}

NLLKf <- function(cvec, SiCell, data, p, k, B, estGrid, weights) {
    .Call(`_mGSFPCA_NLLKf`, cvec, SiCell, data, p, k, B, estGrid, weights)
}

NLLKg <- function(cvec, SiCell, data, p, k, B, estGrid, weights) {
    .Call(`_mGSFPCA_NLLKg`, cvec, SiCell, data, p, k, B, estGrid, weights)
}

get_SiCell <- function(data) {
    .Call(`_mGSFPCA_get_SiCell`, data)
}

topdm_cpp <- function(sig) {
    .Call(`_mGSFPCA_topdm_cpp`, sig)
}

mwGS <- function(U, weights) {
    .Call(`_mGSFPCA_mwGS`, U, weights)
}

